### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by Fangwq** [cunningham-lab/RTGPS#1]
I ran the code with following command:
```
python3 run_sggp.py --dataset=pol --total_n=-1 --kernel_type=rbf
```
And the error in file ```experiment_fns.py``` is that: 
```
from rff.rff_fns import OneOverJ
ModuleNotFoundError: No module named 'rff'
```
It seems that some files are missing. Would you like to upload them ?

**Comment by AndPotap** [comment]
Hi @Fangwq, I added the missing files!

**Comment by Fangwq** [comment]
@AndPotap , thanks for your sharing! By the way,  the ```experiments/loss_ss_rff.py ``` and ```experiments/grid_rff_loss.py``` files are also missing.

**Comment by AndPotap** [comment]
Hi @Fangwq, those two files are not  longer used (I'm updating the README). Look at the file rff.sh to see how RFF is ran now. It uses the file experiments/run_rff.py

**Comment by Fangwq** [comment]
@AndPotap, thanks for the update!
